addSbtPlugin("com.github.gseitz"   % "sbt-release"           % "1.0.5")
addSbtPlugin("com.jsuereth"        % "sbt-pgp"               % "1.0.1")
addSbtPlugin("com.typesafe"        % "sbt-mima-plugin"       % "0.1.14")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"         % "1.5.0")