addSbtPlugin("com.github.gseitz"   % "sbt-release"           % "1.0.13")
addSbtPlugin("com.jsuereth"        % "sbt-pgp"               % "2.0.1")
addSbtPlugin("com.typesafe"        % "sbt-mima-plugin"       % "0.6.2")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"       % "sbt-scoverage"         % "1.6.1")
