addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.14.4")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"         % "2.3.1")
addSbtPlugin("com.github.sbt"     % "sbt-release"     % "1.4.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "1.1.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.5.6")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.8")
